services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: AuthDb
    ports:
      - "5432:5432"

  productservice:
    build: ./ProductService
    depends_on:
      - postgres
    ports:
      - "5001:8080"
    environment:
    - Jwt__Key=SuperSecretKey123456789
    - Jwt__Issuer=AuthService
    - Jwt__Audience=MicroserviceApp

  authservice:
    build: ./AuthService
    depends_on:
      - postgres
    ports:
      - "5002:8080"
    environment:
    - Jwt__Key=SuperSecretKey123456789
    - Jwt__Issuer=AuthService
    - Jwt__Audience=MicroserviceApp

  apigateway:
    build: ./ApiGateway
    depends_on:
      - productservice
      - authservice
    ports:
      - "5000:8080"