services:
  postgres:
    image: postgres:18
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  productservice:
    build: ./ProductService
    depends_on:
      - postgres
    ports:
      - "5001:8080"
    environment:
      Jwt__Key: SuperSecretKey123456789
      Jwt__Issuer: AuthService
      Jwt__Audience: MicroserviceApp

  authservice:
    build: ./AuthService
    depends_on:
      - postgres
    ports:
      - "5002:8080"
    environment:
      Jwt__Key: SuperSecretKey123456789
      Jwt__Issuer: AuthService
      Jwt__Audience: MicroserviceApp

  apigateway:
    build: ./ApiGateway
    depends_on:
      - productservice
      - authservice
    ports:
      - "5000:8080"