version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  productservice:
    build: ./ProductService
    depends_on:
      - postgres
    ports:
      - "5001:8080"

  authservice:
    build: ./AuthService
    depends_on:
      - postgres
    ports:
      - "5002:8080"

  apigateway:
    build: ./ApiGateway
    depends_on:
      - productservice
      - authservice
    ports:
      - "5000:8080"